### ISSUE TITLE
Muse 2 disconnection issue in Python

### ISSUE THREAD

**Issue by ChilloutCharles** [brainflow-dev/brainflow#522] opened 2022-07-15 17:41 UTC
**Describe the bug**
Muse 2 Headband stops sending data after a few minutes with no error

**To Reproduce**
using a modified version of the brainflow_get_data test attached: [brainflow_get_data.py.txt](https://github.com/brainflow-dev/brainflow/files/9122887/brainflow_get_data.py.txt)

**Info (please complete the following information):**
 - Board Id : 38
 - OS running on your PC: Windows 10 Version 21H2
 - Programming Language and its version: Python 3.8.5
 - Architecture(x86, x64, ARM, etc): x64
 - Python Pip List: [piplist.txt](https://github.com/brainflow-dev/brainflow/files/9122872/piplist.txt)

**Expected behavior**
Muse 2 headband should continue to send information.

**Additional context**
Logfile attached: [board_log_file.txt](https://github.com/brainflow-dev/brainflow/files/9122860/board_log_file.txt)

**Comment by Andrey1994** [comment] 2022-07-15 17:44
there will be a release next week with plenty of fixes for muse boards, would be good if you test it one more time after it

**Comment by ChilloutCharles** [comment] 2022-07-15 18:13
> there will be a release next week with plenty of fixes for muse boards, would be good if you test it one more time after it

Thanks! I'll be looking forward to it. Will close when I encounter no issues with it

**Comment by Andrey1994** [comment] 2022-07-16 11:24
https://github.com/brainflow-dev/brainflow/issues/393 it also can be relevant

**Comment by ChilloutCharles** [comment] 2022-07-25 14:36
I use my muse with a dongle, so I should be good to avoid that. Any news on that release?

**Comment by Andrey1994** [comment] 2022-07-25 15:12
will be published today, I already merged this pr to master

**Comment by Andrey1994** [comment] 2022-07-25 19:25
tried with latest release and muse s. cannot reproduce, closing this now. feel free to reopen if its still an issue also check the battery first

**Closed by Andrey1994** 2022-07-25 19:25 UTC
Labels: bug

**Comment by ChilloutCharles** [comment] 2022-07-26 06:10
Looks good so far, but somehow I lost ppg with my muse 2. Will write a different issue later today.

**Comment by Andrey1994** [comment] 2022-07-26 06:25
Its not an issue, read release post
